language: android

jdk:
 - openjdk17

android:
  components:
    - tools
    - platform-tools
    - build-tools-35.0.0
    - android-35
    - extra-android-m2repository
    - extra-google-m2repository

script:
  - ./gradlew clean check assemble -Dpre-dex=false

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
